import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

NUM_CLIENTS = 24
NUM_ROUNDS = 50
EPOCHS_PER_CLIENT = 3
BATCH_SIZE = 32
LEARNING_RATE = 0.001

PERCENT_MALICIOUS = 0.25
POISON_FACTOR = 50

NUM_SAMPLES_PER_CLIENT = 500
NUM_FEATURES = 30
DATA_SPLIT_ALPHA = 0.5

DP_NOISE_STD_DEV = 0.05
TOTAL_PRIVACY_BUDGET_EPSILON = 10.0
PRIVACY_COST_PER_ROUND = 0.1

REPUTATION_ALPHA = 0.5
REPUTATION_BETA = 0.3
REPUTATION_GAMMA = 0.2
INITIAL_REPUTATION = 1.0
REPUTATION_THRESHOLD = 0.3
MAX_CONSENSUS_DEVIATION = 50.0

ROLLBACK_THRESHOLD = 0.02

NUM_SIDECHAINS = 3
IBC_SYNC_INTERVAL = 5

PLOT_RESULTS = True